import org.hoshino9.engine.galtext.*

object Section1 : GalSection {
    override val name: String = "自然之美"

    override val launcher: GalLauncher
        get() = gal {
            none say "早上"
            ti say "诶……旅游？"
            self say "也说不上是旅游啦，只是出门玩玩而已"
            ti say "唔……"
            self say "话说……天怡有出去玩过吗？"
            ti say "没有……"
            self say "那正好，带天怡出去玩一玩"
            ti say "嗯……"

            none say "天怡随后叫醒了熟睡的天忆，与天诚一起踏上了旅行的道路"
            tt say "啊……哇！是森林！"
            ti say "诶……明明家旁边也是森林"
            tt say "不一样的！"
            ti say "诶……"
            none say "天怡看向天诚"
            ti say "姐姐是了解到天忆是植物魔法使……才来森林玩的吗……"
            self say "嗯，而且这片森林很不错哦"
            ti say "唔……"
            self say "好啦，快走吧"

            ti say "诶……哪来的帐篷……"
            self say "嗯？我早早就在隙间里准备好的……"
            ti say "唔……隙间……隙间魔法？"
            self say "嗯"
            ti say "诶……"
            self say "找时间我也教一教天怡吧，天怡是星曜魔法使，应该很适合隙间魔法的"
            ti say "嗯……"
            self say "来，帮我一下"
            ti say "啊……嗯！"

            ti say "诶……天忆"
            tt say "唔？"
            ti say "不要跑太远了呀，待会迷路了就糟糕了……"
            tt say "唔嗯……"

            ti say "诶……钓鱼……我不会……"
            self say "很简单的啦，来，我教你"
            ti say "唔诶……"
            none say "天诚将鱼钩用力甩到池塘里"
            ti say "唔……"
            none say "过了好久一段时间"
            ti say "唔…………"
            self say "再……再等等嘛……"
            ti say "会不会……根本没有鱼啊……"
            tt say "嘿！"
            none say "天忆突然跳进池塘里"
            tt say "抓到鱼啦！"
            ti say "啊！天忆！"
            none say "天怡跑到天忆身边"
            ti say "真是的……这样会着凉的……"
            tt say "呜诶……对不起……"
            tt say "不过，姐姐！鱼！"
            ti say "嗯……知道啦……先过来吧，我帮你烘干一下衣服……"

            tt say "呼啊~好暖和~"
            self say "嘿！"
            none say "天诚用力拉起鱼竿，鱼钩上吊着一条大鱼"
            self say "好啦，天忆也只是像玩一玩而已"
            ti say "我……我也没有责怪天忆的意思……只是万一着凉了……"
            self say "诶……天忆是不怕着凉的哦？"
            ti say "诶……？"
            self say "天怡原来还不知道吗……那等晚上我好好跟天怡说说"
            ti say "嗯……"
            ti say "那鱼……姐姐打算怎么弄呢？"
            self say "烤鱼呀，烤鱼很好吃的"
            ti say "烧烤吗……"
            self say "嗯"

            self say "来，天忆"
            tt say "唔？"
            self say "我来教你一个魔法"
            tt say "魔法……"
            self say "啊……看得懂魔法阵吗？"
            none say "天忆摇摇头"
            self say "那……等等哦……"
            none say "天诚从隙间里拿出一张小卡片"
            self say "只要往里面灌输魔力就可以了，试试看吧"
            tt say "诶……不会像姐姐那样……爆炸吗？"
            ti say "诶？"
            self say "不会啦，就算魔力输出过量也只是卡片烧掉而已"
            tt say "那……天忆试试！"
            none say "天忆慢慢往里面灌入魔力"
            none say "慢慢地，慢慢地……"
            none say "魔力充满了整张卡片"
            none say "接着化作粒子消散在空气中"
            tt say "诶……烧掉了……"
            self say "不是啦，天怡拿一桶水过来"
            ti say "好"
            none say "天怡双手提着水走来"
            none say "天诚拿过水桶"
            none say "倒在了天忆身上"
            tt say "唔诶……呜哇！！！！"
            none say "天忆遮住眼睛"
            ti say "姐姐！"
            tt say "呜！……"
            self say "怎么样，没淋湿吧？"
            tt say "呜……诶？"
            none say "天忆睁开眼睛，看着自己的身体"
            tt say "呜哇……好神奇……"
            self say "话说……孤儿院是没有教魔法吗？"
            ti say "只是教一些简单的而已……"
            self say "好吧，那接下来可能得送你们去上学了呢……"
            ti say "上学……？真的吗！？"
            self say "当然啦，不过天怡好像很期待的样子？"
            ti say "嗯！……不过天忆可能不太喜欢，孤儿院的课都没有认真听过"
            self say "诶……"
            none say "天诚看向天忆"
            tt say "唔？"
            self say "不学魔法可不行哦"
            tt say "呜诶……但是……学习好无聊……"
            self say "没有魔法的世界更无聊哦"
            tt say "呜……"
            self say "好啦，天忆好像很喜欢在水里抓鱼的样子，那这次就抓个够哦"
            tt say "嗯！"

            ti say "呼……姐姐刚才真的是吓了我一大跳呢……"
            none say "天诚笑了笑"
            self say "你以为我想做什么？"
            ti say "没……没有……"
            self say "而且呀，不觉得看着天忆开心的样子……很幸福吗？"
            ti say "诶……？"
            ti say "唔……不是很懂……"
        }
}