import org.hoshino9.engine.galtext.*

object Section1 : GalSection {
    override val name: String = "自然之美"

    override val launcher: GalLauncher
        get() = gal {
            none say "早上"
            ti say "诶……旅游？"
            self say "也说不上是旅游啦，只是出门玩玩而已"
            ti say "唔……"
            self say "话说……天怡有出去玩过吗？"
            ti say "没有……"
            self say "那正好，带天怡出去玩一玩"
            ti say "嗯……"

            none say "天怡随后叫醒了熟睡的天忆，与天诚一起踏上了旅行的道路"
            tt say "啊……哇！是森林！"
            ti say "诶……明明家旁边也是森林"
            tt say "不一样的！"
            ti say "诶……"
            none say "天怡看向天诚"
            ti say "姐姐是了解到天忆是植物魔法使……才来森林玩的吗……"
            self say "嗯，而且这片森林很不错哦"
            ti say "唔……"
            self say "好啦，快走吧"

            ti say "诶……哪来的帐篷……"
            self say "嗯？我早早就在隙间里准备好的……"
            ti say "唔……隙间……隙间魔法？"
            self say "嗯"
            ti say "诶……"
            self say "找时间我也教一教天怡吧，天怡是星曜魔法使，应该很适合隙间魔法的"
            ti say "嗯……"
            self say "来，帮我一下"
            ti say "啊……嗯！"

            ti say "诶……天忆"
            tt say "唔？"
            ti say "不要跑太远了呀，待会迷路了就糟糕了……"
            tt say "唔嗯……"

            ti say "诶……钓鱼……我不会……"
            self say "很简单的啦，来，我教你"
            ti say "唔诶……"
            none say "天诚将鱼钩用力甩到池塘里"
            ti say "唔……"
            none say "过了好久一段时间"
            ti say "唔…………"
            self say "再……再等等嘛……"
            ti say "会不会……根本没有鱼啊……"
            tt say "嘿！"
            none say "天忆突然跳进池塘里"
            tt say "抓到鱼啦！"
            ti say "啊！天忆！"
            none say "天怡跑到天忆身边"
            ti say "真是的……这样会着凉的……"
            tt say "呜诶……对不起……"
            tt say "不过，姐姐！鱼！"
            ti say "嗯……知道啦……先过来吧，我帮你烘干一下衣服……"

            tt say "呼啊~好暖和~"
            self say "嘿！"
            none say "天诚用力拉起鱼竿，鱼钩上吊着一条大鱼"
            self say "好啦，天忆也只是像玩一玩而已"
            ti say "我……我也没有责怪天忆的意思……只是万一着凉了……"
            self say "诶……天忆是不怕着凉的哦？"
            ti say "诶……？"
            self say "天怡原来还不知道吗……那等晚上我好好跟天怡说说"
            ti say "嗯……"
            ti say "那鱼……姐姐打算怎么弄呢？"
            self say "烤鱼呀，烤鱼很好吃的"
            ti say "烧烤吗……"
            self say "嗯"
        }
}