import org.hoshino9.engine.galtext.*

object Section1 : GalSection {
    override val name: String = "自然之美"

    override val launcher: GalLauncher<Context>
        get() = gal {
            none say "早上"
            ti say "诶……旅游？"
            self say "也说不上是旅游啦，只是出门玩玩而已"
            ti say "唔……"
            self say "话说……天怡有出去玩过吗？"
            ti say "没有……"
            self say "那正好，带天怡出去玩一玩"
            ti say "嗯……"

            none say "天怡随后叫醒了熟睡的天忆，与天诚一起踏上了旅行的道路"
            tt say "啊……哇！是森林！"
            ti say "诶……明明家旁边也是森林"
            tt say "不一样的！"
            ti say "诶……"
            none say "天怡看向天诚"
            ti say "姐姐是了解到天忆是植物魔法使……才来森林玩的吗……"
            self say "嗯，而且这片森林很不错哦"
            ti say "唔……"
            self say "好啦，快走吧"

            ti say "诶……哪来的帐篷……"
            self say "嗯？我早早就在隙间里准备好的……"
            ti say "唔……隙间……隙间魔法？"
            self say "嗯"
            ti say "诶……"
            self say "找时间我也教一教天怡吧，天怡是星曜魔法使，应该很适合隙间魔法的"
            ti say "嗯……"
            self say "来，帮我一下"
            ti say "啊……嗯！"

            ti say "诶……天忆"
            tt say "唔？"
            ti say "不要跑太远了呀，待会迷路了就糟糕了……"
            tt say "唔嗯……"

            ti say "诶……钓鱼……我不会……"
            self say "很简单的啦，来，我教你"
            ti say "唔诶……"
            none say "天诚将鱼钩用力甩到池塘里"
            ti say "唔……"
            none say "过了好久一段时间"
            ti say "唔…………"
            self say "再……再等等嘛……"
            ti say "会不会……根本没有鱼啊……"
            tt say "嘿！"
            none say "天忆突然跳进池塘里"
            tt say "抓到鱼啦！"
            ti say "啊！天忆！"
            none say "天怡跑到天忆身边"
            ti say "真是的……这样会着凉的……"
            tt say "呜诶……对不起……"
            tt say "不过，姐姐！鱼！"
            ti say "嗯……知道啦……先过来吧，我帮你烘干一下衣服……"

            tt say "呼啊~好暖和~"
            self say "嘿！"
            none say "天诚用力拉起鱼竿，鱼钩上吊着一条大鱼"
            self say "好啦，天忆也只是像玩一玩而已"
            ti say "我……我也没有责怪天忆的意思……只是万一着凉了……"
            self say "诶……天忆是不怕着凉的哦？"
            ti say "诶……？"
            self say "天怡原来还不知道吗……那等晚上我好好跟天怡说说"
            ti say "嗯……"
            ti say "那鱼……姐姐打算怎么弄呢？"
            self say "烤鱼呀，烤鱼很好吃的"
            ti say "烧烤吗……"
            self say "嗯"

            self say "来，天忆"
            tt say "唔？"
            self say "我来教你一个魔法"
            tt say "魔法……"
            self say "啊……看得懂魔法阵吗？"
            none say "天忆摇摇头"
            self say "那……等等哦……"
            none say "天诚从隙间里拿出一张小卡片"
            self say "只要往里面灌输魔力就可以了，试试看吧"
            tt say "诶……不会像姐姐那样……爆炸吗？"
            ti say "诶？"
            self say "不会啦，就算魔力输出过量也只是卡片烧掉而已"
            tt say "那……天忆试试！"
            none say "天忆慢慢往里面灌入魔力"
            none say "慢慢地，慢慢地……"
            none say "魔力充满了整张卡片"
            none say "接着化作粒子消散在空气中"
            tt say "诶……烧掉了……"
            self say "不是啦，天怡拿一桶水过来"
            ti say "好"
            none say "天怡双手提着水走来"
            none say "天诚拿过水桶"
            none say "倒在了天忆身上"
            tt say "唔诶……呜哇！！！！"
            none say "天忆遮住眼睛"
            ti say "姐姐！"
            tt say "呜！……"
            self say "怎么样，没淋湿吧？"
            tt say "呜……诶？"
            none say "天忆睁开眼睛，看着自己的身体"
            tt say "呜哇……好神奇……"
            self say "话说……孤儿院是没有教魔法吗？"
            ti say "只是教一些简单的而已……"
            self say "好吧，那接下来可能得送你们去上学了呢……"
            ti say "上学……？真的吗！？"
            self say "当然啦，不过天怡好像很期待的样子？"
            ti say "嗯！……不过天忆可能不太喜欢，孤儿院的课都没有认真听过"
            self say "诶……"
            none say "天诚看向天忆"
            tt say "唔？"
            self say "不学魔法可不行哦"
            tt say "呜诶……但是……学习好无聊……"
            self say "没有魔法的世界更无聊哦"
            tt say "呜……"
            self say "好啦，天忆好像很喜欢在水里抓鱼的样子，那这次就抓个够哦"
            tt say "嗯！"

            ti say "呼……姐姐刚才真的是吓了我一大跳呢……"
            none say "天诚笑了笑"
            self say "你以为我想做什么？"
            ti say "没……没有……"
            self say "而且呀，不觉得看着天忆开心的样子……很幸福吗？"
            ti say "诶……？"
            ti say "唔……不是很懂……"

            none say "正午"
            listOf(tt, ti) say "呼哇~好舒服~"
            none say "两人正躺在毯子上晒着太阳"
            self say "偶尔出来玩玩也不错吧？"
            ti say "嗯！"
            tt say "呼~"
            self say "好好休息一下吧，天忆应该也累了"
            tt say "唔嗯……"

            none say "夜晚"
            self say "天忆还没起床吗……都已经到晚上了……"
            ti say "唔……有的时候天忆的确会睡得久一些……"
            self say "是吗……"
            tt say "呜……姐姐……"
            self say "嗯？"
            self say "啊……说梦话啊……"
            ti say "天忆其实……会经常做噩梦"
            self say "做噩梦吗……"
            none say "是那个吗？"
            none say "天诚胡思乱想着些什么"
            ti say "姐姐……？"
            self say "……啊？"
            ti say "姐姐在发呆吗？"
            self say "嗯……想到了一些事情……"
            ti say "什么事情？"
            self say "没什么，啊，趁这个时候来教天怡魔法吧"
            ti say "啊……嗯！"

            tt say "呜……"
            self say "啊……天忆醒啦？"
            tt say "诶……姐姐……呜呜……"
            none say "天忆突然哭泣起来"
            none say "泪珠沿着天忆的脸颊滴落"
            self say "怎么了？做噩梦了？"
            tt say "呜呜……"
            tt say "呜嗯……"
            none say "天怡早就睡着了，这个时候能够安慰天忆的只有天诚了"
            none say "天诚抱住天忆"
            self say "梦到什么了？"
            none say "天诚一边问道，一边慢慢地摸着天忆的头"
            none say "仿佛这样能给予天忆安全感"
            tt say "梦到……姐姐不要天忆了……"

            switch("tenied_h") {
                tt say "梦到姐姐……只要天怡姐姐……把天忆丢掉了……"
            }

            self say "怎么会呢，只是梦而已啦……"
            tt say "呜……"
            none say "天诚紧紧抱着天忆"
            none say "天忆的哭声也渐渐消失了"

            switch("tenied_h") {
                tt say "姐……姐姐……"
                self say "嗯？"
                tt say "上次……姐姐和天怡姐姐在卧室……做那种事情……"
                self say "诶？"
                tt say "是什么呢……？"
                self say "……"
                self say "只是在玩而已啦"
                none say "天诚打算糊弄过去"
                tt say "那……天忆也可以和姐姐玩吗？"
                self say "诶？"
                tt say "总感觉……有一个声音……想让天忆去玩的样子……"
                self say "……"
                self say "是吗……"
                tt say "所以姐姐……可以陪天忆玩吗？"
                self say "以后再说啦……"
                none say "天诚摸着天忆的头"
                none say "是因为天怡在旁边所以才暂时推迟一下吗"
                tt say "呜嗯……"
            }

            self say "天忆还睡得着吗？"
            tt say "唔……"
            self say "要是睡不着的话，看会儿星星吧？"

            none say "帐篷外，星空闪耀"
            none say "二人坐在草地上，仰望着璀璨星辰"
            none say "一切都那么的祥和，宁静"
            self say "听天怡说，天忆经常做噩梦？"
            tt say "嗯……"
            tt say "经常做噩梦的天忆……是不是很坏……"
            self say "没有啦，做噩梦这种东西自己是控制不了的啦……"
            tt say "唔……"
            none say "天忆碧蓝的眼中反射出星星的光芒"
            tt say "不过……不做噩梦的天忆会更好吧……"
            self say "嗯……我倒是无所谓……我挺喜欢安慰人的"
            tt say "唔…………"
            self say "啊……趁现在让我来了解一下天忆吧"
            tt say "诶"
            self say "天忆喜欢吃什么呢？"
            tt say "唔……水果……"
            self say "什么水果？"
            tt say "只要是水果都喜欢！"
            self say "嗯……"
            self say "喜欢星星吗？"
            tt say "喜欢！"
            self say "来，拿着这个"
            tt say "唔……又是魔法卡片？"
            self say "嗯，像之前一样灌入魔力吧"
            tt say "嗯！"
            none say "魔力渐渐充满了整张卡片"
            none say "突然，卡片化作粒子，在两人身旁构建出一个结界"
            tt say "呜……啊！"
            none say "满是星星的结界"
            none say "天忆兴奋地站起来，触碰着空中的星星"
            none say "星星仿佛回应呼唤一般，飞到了天忆的手中"
            tt say "是星星！"
            self say "喜欢吗？"
            tt say "嗯！"
            tt say "不过……突然好困……"
            self say "困就睡觉吧，时候也不早了呢"
            tt say "嗯……"
            none say "天忆躺在天诚的大腿上"
            none say "星星结界也缓缓消散"
            self say "真是可爱的孩子呢……"

            ti say "姐姐……？"
            self say "啊……天怡？"
            ti say "姐姐怎么在这种地方睡着了，会感冒的"
            self say "唔……"
            none say "天诚迷迷糊糊地坐了起来"
            self say "因为天忆睡着了，又不想吵醒她，所以就在这里睡着啦……"
            ti say "唔……"
            self say "天忆？"
            none say "天诚晃了晃天忆"
            none say "但天忆仍然沉睡在美梦中"
            self say "啊……天怡把天忆抱到帐篷里去吧，我来准备早餐"
            ti say "嗯"

            ti say "姐姐这是在做什么呀？"
            self say "豆浆，喝过吗？"
            ti say "有喝过……"
            ti say "现在是在磨豆浆吗？"
            self say "嗯，隙间里没有现成的，所以就现磨啦"
            ti say "唔……我也想试试看"
            self say "呐，这个给你"
            ti say "魔法卡片？"
            self say "嗯"
            none say "天怡把魔力灌入卡片"
            none say "随后卡片化作一个小球"
            self say "然后往里面放入豆子就行了"
            ti say "嗯……"
            none say "天怡往小球内丢入豆子"
            none say "接着小球开始旋转"
            ti say "噢哦哦！"
            self say "要等一会儿哦，磨完豆子之后还得分离豆浆和豆渣，要用到另一张魔法卡片"
            ti say "嗯！"
        }
}